### ISSUE TITLE
Hello Cardboard black screen and crash 

### ISSUE THREAD

**Issue by magiwanders** [googlevr/cardboard#139]
Setup and compiling work fine. I followed the quick start, however my phone (android 10) shows completely black screen (not even the x or cogwheel) and crashes when any interaction is given. This is bug report.

java.lang.Error: FATAL EXCEPTION [main]
Unity version     : 2019.4.12f1
Device model      : Xiaomi Mi 9T Pro

Caused by: java.lang.Error: * * * * * * * * * * * * * * * *
Version '2019.4.12f1 (225e826a680e)', Build type 'Release', Scripting Backend 'il2cpp', CPU 'arm64-v8a'

Revision: '0'
ABI: 'arm64'
Timestamp: 2020-10-09 16:26:17+0200

signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
    x0  0000000000000000  x1  0000000000006567  x2  0000000000000006  x3  0000007951b0a6e0
    x4  fefeff7850afaf1f  x5  fefeff7850afaf1f  x6  fefeff7850afaf1f  x7  7f7f7f7f7fffff7f
    x8  00000000000000f0  x9  45d6eb67ceb6da18  x10 0000000000000001  x11 0000000000000000
    x12 fffffff0fffffbdf  x13 ffffffffffffffff  x14 0000000000000004  x15 ffffffffffffffff
    x16 0000007abcd34738  x17 0000007abcd12d20  x18 0000000000008006  x19 0000000000006531
    x20 0000000000006567  x21 00000000ffffffff  x22 00000079ba3fca40  x23 00000079d13defc4
    x24 0000000000000000  x25 00000000000027b5  x26 0000007951b0b020  x27 00000079d07ea410
    x28 00000079ba3fcb08  x29 0000007951b0a780
    sp  0000007951b0a6c0  lr  0000007abccc4404  pc  0000007abccc4430

backtrace:
      #00 pc 0000000000073430  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160) (BuildId: 084c8a81b8c78e19cd9a1ff6208e77cf)
      #01 pc 00000000000648a0  /data/app/com.MagiWanders.VRAUDIO_Experiments-yK8pwBaSl6KTB50ws1DF6w==/lib/arm64/libcardboard_api.so (BuildId: dd90749eb9a668980e1490134d06648632804b11)
      #02 pc 00000000000655ec  /data/app/com.MagiWanders.VRAUDIO_Experiments-yK8pwBaSl6KTB50ws1DF6w==/lib/arm64/libcardboard_api.so (cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams)+552) (BuildId: dd90749eb9a668980e1490134d06648632804b11)
      #03 pc 00000000000636f4  /data/app/com.MagiWanders.VRAUDIO_Experiments-yK8pwBaSl6KTB50ws1DF6w==/lib/arm64/libcardboard_api.so (cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidgets()+164) (BuildId: dd90749eb9a668980e1490134d06648632804b11)
      #04 pc 0000000000063640  /data/app/com.MagiWanders.VRAUDIO_Experiments-yK8pwBaSl6KTB50ws1DF6w==/lib/arm64/libcardboard_api.so (cardboard::unity::CardboardApi::RenderWidgets()+24) (BuildId: dd90749eb9a668980e1490134d06648632804b11)
      #05 pc 0000000000067e3c  /data/app/com.MagiWanders.VRAUDIO_Experiments-yK8pwBaSl6KTB50ws1DF6w==/lib/arm64/libcardboard_api.so (BuildId: dd90749eb9a668980e1490134d06648632804b11)
      #06 pc 0000000000067d64  /data/app/com.MagiWanders.VRAUDIO_Experiments-yK8pwBaSl6KTB50ws1DF6w==/lib/arm64/libcardboard_api.so (BuildId: dd90749eb9a668980e1490134d06648632804b11)
      #07 pc 0000000000067d2c  /data/app/com.MagiWanders.VRAUDIO_Experiments-yK8pwBaSl6KTB50ws1DF6w==/lib/arm64/libcardboard_api.so (BuildId: dd90749eb9a668980e1490134d06648632804b11)
      #08 pc 0000000000412020  /data/app/com.MagiWanders.VRAUDIO_Experiments-yK8pwBaSl6KTB50ws1DF6w==/lib/arm64/libunity.so (BuildId: 7dba3fe75ee52595eb5ab81881a8895928616c15)
      #09 pc 00000000004b012c  /data/app/com.MagiWanders.VRAUDIO_Experiments-yK8pwBaSl6KTB50ws1DF6w==/lib/arm64/libunity.so (BuildId: 7dba3fe75ee52595eb5ab81881a8895928616c15)
      #10 pc 00000000004b0c78  /data/app/com.MagiWanders.VRAUDIO_Experiments-yK8pwBaSl6KTB50ws1DF6w==/lib/arm64/libunity.so (BuildId: 7dba3fe75ee52595eb5ab81881a8895928616c15)
      #11 pc 00000000004a8074  /data/app/com.MagiWanders.VRAUDIO_Experiments-yK8pwBaSl6KTB50ws1DF6w==/lib/arm64/libunity.so (BuildId: 7dba3fe75ee52595eb5ab81881a8895928616c15)
      #12 pc 00000000001fb638  /data/app/com.MagiWanders.VRAUDIO_Experiments-yK8pwBaSl6KTB50ws1DF6w==/lib/arm64/libunity.so (BuildId: 7dba3fe75ee52595eb5ab81881a8895928616c15)
      #13 pc 00000000000d6cb0  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+36) (BuildId: 084c8a81b8c78e19cd9a1ff6208e77cf)
      #14 pc 0000000000074eac  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 084c8a81b8c78e19cd9a1ff6208e77cf)

	at libc.abort(abort:160)
	at libcardboard_api.0x648a0(Native Method)
	at libcardboard_api.cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidget(cardboard::unity::CardboardApi::WidgetParams)(RenderWidget:552)
	at libcardboard_api.cardboard::unity::CardboardApi::CardboardApiImpl::RenderWidgets()(RenderWidgets:164)
	at libcardboard_api.cardboard::unity::CardboardApi::RenderWidgets()(RenderWidgets:24)
	at libcardboard_api.0x67e3c(Native Method)
	at libcardboard_api.0x67d64(Native Method)
	at libcardboard_api.0x67d2c(Native Method)
	at libunity.0x412020(Native Method)
	at libunity.0x4b012c(Native Method)
	at libunity.0x4b0c78(Native Method)
	at libunity.0x4a8074(Native Method)
	at libunity.0x1fb638(Native Method)
	at libc._pthread_start(void*)(_pthread_start:36)
	at libc._start_thread(_start_thread:64)

**Comment by magiwanders** [comment]
Seems to be very similar to https://github.com/googlevr/cardboard/issues/120

**Comment by magiwanders** [comment]
OpenGLES3 was selected instead of OpenGLES2.
