### ISSUE TITLE
Crash when scanning QR Code after Gradle Plugin Update

### ISSUE THREAD

**Issue by cversek** [googlevr/cardboard#239]
After Android Studio updates to the recommended the Gradle plugin (from 3.6.1 -> 4.1.2) the "Switch Viewer" QR code scanning crashes when tested with the hello-android app:
```logcat
2021-03-31 00:41:20.931 18059-18059/com.google.cardboard.hellocardboard E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.cardboard.hellocardboard, PID: 18059
    java.lang.RuntimeException: Unable to pause activity {com.google.cardboard.hellocardboard/com.google.cardboard.sdk.QrCodeCaptureActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Thread$State java.lang.Thread.getState()' on a null object reference
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4745)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4696)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4647)
        at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Thread$State java.lang.Thread.getState()' on a null object reference
        at com.google.cardboard.sdk.qrcode.camera.CameraSource$FrameProcessingRunnable.release(CameraSource.java:501)
        at com.google.cardboard.sdk.qrcode.camera.CameraSource.release(CameraSource.java:124)
        at com.google.cardboard.sdk.qrcode.camera.CameraSourcePreview.release(CameraSourcePreview.java:76)
        at com.google.cardboard.sdk.QrCodeCaptureActivity.onPause(QrCodeCaptureActivity.java:211)
        at android.app.Activity.performPause(Activity.java:8174)
        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1510)
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:4735)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:4696) 
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:4647) 
        at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:46) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

**Comment by jballoffet** [comment]
Thanks for reaching out to us and reporting this issue! I confirm I can repro it when scanning a QR code. A ticket for debugging and fixing this issue has been added to our backlog and will be prioritized along with other issues.

**Comment by dipinarora9** [comment]
I was able to fix this issue by commenting out the assert.
https://github.com/eduhub-croatia/cardboard/blob/master/sdk/qrcode/android/java/com/google/cardboard/sdk/qrcode/camera/CameraSource.java#L501

Not sure if this is a safe way to fix this. But the app seems to be working fine after commenting the assert.
