### ISSUE TITLE
Unable to instantiate appComponentFactory

### ISSUE THREAD

**Issue by ArthurAtlantico** [googlevr/cardboard#42]
Followed the Unity tutorial. Build results in a black screen. App crashes when I touch the screen.

2020-05-21 10:41:22.545 767-767/? E/LoadedApk: Unable to instantiate appComponentFactory
    java.lang.ClassNotFoundException: Didn't find class "androidx.core.app.CoreComponentFactory" on path: DexPathList[[zip file "/data/app/com.instagram.android-7aox3UmhV35HFFlmKp2eow==/base.apk", zip file "/data/app/com.instagram.android-7aox3UmhV35HFFlmKp2eow==/split_arservicesforpersonsegmentation.apk", zip file "/data/app/com.instagram.android-7aox3UmhV35HFFlmKp2eow==/split_caffe2.apk"],nativeLibraryDirectories=[/data/app/com.instagram.android-7aox3UmhV35HFFlmKp2eow==/lib/arm64, /data/app/com.instagram.android-7aox3UmhV35HFFlmKp2eow==/base.apk!/lib/arm64-v8a, /data/app/com.instagram.android-7aox3UmhV35HFFlmKp2eow==/split_arservicesforpersonsegmentation.apk!/lib/arm64-v8a, /data/app/com.instagram.android-7aox3UmhV35HFFlmKp2eow==/split_caffe2.apk!/lib/arm64-v8a, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:273)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:896)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:991)
        at android.app.LoadedApk.getResources(LoadedApk.java:1248)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2616)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2608)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6737)
        at android.app.ActivityThread.access$1300(ActivityThread.java:268)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1982)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7814)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.instagram.android-7aox3UmhV35HFFlmKp2eow==/split_arservicesforpersonsegmentation.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:365)
        at dalvik.system.DexFile.<init>(DexFile.java:107)
        at dalvik.system.DexFile.<init>(DexFile.java:80)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:465)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:424)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:126)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:101)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:74)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:87)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:116)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:114)
        at android.app.ApplicationLoaders.getClassLoaderWithSharedLibraries(ApplicationLoaders.java:60)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:892)
        		... 13 more
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.instagram.android-7aox3UmhV35HFFlmKp2eow==/split_caffe2.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:365)
        at dalvik.system.DexFile.<init>(DexFile.java:107)
        at dalvik.system.DexFile.<init>(DexFile.java:80)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:465)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:424)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:126)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:101)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:74)

**Comment by ArthurAtlantico** [comment]
Issue is solved by setting OpenGLES2 in Graphics APIs. Build results in a black screen with two icons and a middle vertical line, though.

**Comment by ArthurAtlantico** [comment]
Also, not sure if it is relevant but this screen shows up BEFORE the splash screen.

**Comment by ArthurAtlantico** [comment]
Unchecking Initialize XR on Startup results in a crash right after the splash screen.

**Comment by ArthurAtlantico** [comment]
I managed to get it working with Unity Personal using these settings:

Player->XR Settings:
Under Deprecated Settings...
Check Virtual Reality Supported
Add None to Virtual Reality SDKs

XR Plugin-in Management:
On the Android tab...
Check Initialize XR on Startup
Check Cardboard XR Plugin

I am using Unity 2019.3.14.f1
