### ISSUE TITLE
ClassNotFoundException in Cardboard_initializeAndroid

### ISSUE THREAD

**Issue by bl4ckb0ne** [googlevr/cardboard#485]
### SPECIFIC ISSUE ENCOUNTERED

I am writing a Google Cardboard driver for [monado](https://gitlab.freedesktop.org/monado/monado). When launching an application (helloXR in this case, the `.apk` is available on the [OpenXR-SDK](https://github.com/KhronosGroup/OpenXR-SDK-Source/releases) release page), the application is closing and I have the following error message in the logs

```
12-05 14:39:13.228  6743  6774 I 100     : Open /data/app/~~JszHwhdspSFSxjKmvU3P8w==/org.freedesktop.monado.openxr_runtime.in_process-c5jji3g_nUG-cA2_oyUXFA==/base.apk took:660ms
12-05 14:39:13.069  2331  2331 I chatty  : uid=10190(com.android.systemui) identical 4 lines
12-05 14:39:13.070  2331  2331 D KeyButtonRipple:  draw SupportHardware=true Type=ROUNDED_RECT
12-05 14:39:13.233  6743  6774 W System.err: java.lang.ClassNotFoundException: Didn't find class "com.google.cardboard.sdk.qrcode.CardboardParamsUtils" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/system/lib64, /system_ext/lib64, /system/lib64, /system_ext/lib64]]
12-05 14:39:13.234  6743  6774 W System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
12-05 14:39:13.234  6743  6774 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
12-05 14:39:13.234  6743  6774 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
12-05 14:39:13.234  6743  6774 W System.err: java.lang.ClassNotFoundException: Didn't find class "com.google.cardboard.sdk.QrCodeCaptureActivity" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/system/lib64, /system_ext/lib64, /system/lib64, /system_ext/lib64]]
12-05 14:39:13.234  6743  6774 W System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
12-05 14:39:13.234  6743  6774 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
12-05 14:39:13.234  6743  6774 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
12-05 14:39:13.235  6743  6774 F hello_xr.vulka: java_vm_ext.cc:577] JNI DETECTED ERROR IN APPLICATION: RegisterNatives received NULL jclass
12-05 14:39:13.235  6743  6774 F hello_xr.vulka: java_vm_ext.cc:577]     in call to RegisterNatives
```

Followed by a very lengthy stacktrace.

We are using a `minSdk` of 26 so MultiDex should be enabled by default. 

### SMARTPHONE (please complete the following information):
- Device: OnePlus Nord N100 and Google Pixel 6
- OS
  - [x] Android
  - [ ] iOS
- OS version 11 & 15

### STEPS TO REPRODUCE THE ISSUE
1. Install the following APKS:
    - [monado inProcess build of the Cardboard MR](https://gitlab.freedesktop.org/monado/monado/-/jobs/67802224/artifacts/file/src/xrt/targets/openxr_android/build/outputs/apk/inProcess/debug/openxr_android-inProcess-debug.apk)
    - [OpenXR Runtime broker](https://play.google.com/store/apps/details?id=org.khronos.openxr.runtime_broker)
    - [helloXR](https://github.com/KhronosGroup/OpenXR-SDK-Source/releases/download/release-1.1.42/hello_xr-Vulkan-release-1.1.42.apk)
2. Make sure the Monado in Process is enabled in the OpenXR Runtime Broker
3. Start HelloXR
4. Observe the crash in `adb logcat`

### EXPECTED BEHAVIOR

`Cardboard_initializeAndroid` runs successfully and the helloXR application launches.

### VERSIONS USED
**What version of Google Cardboard are you using?**
Cardboard SDK 1.26.0 

### LINK TO A REPOSITORY WITH CODE TO REPRODUCE THE BUG
https://gitlab.freedesktop.org/monado/monado/-/merge_requests/2363

**Comment by XRAdventure** [comment]
Hello,  

I'm having the exact same issue, but from a build made with **Unity 6**, version: **6000.0.30f1 LTS**.  

**Device:** Pixel 4XL  
**Android Version:** 13  

**Error Logs from the APK**

```
java.lang.ClassNotFoundException: com.google.cardboard.sdk.qrcode.CardboardParamsUtils
java.lang.ClassNotFoundException: com.google.cardboard.sdk.QrCodeCaptureActivity
```

It should be noted that in previous versions of Unity I don't have this problem, everything worked as expected.

**Comment by rjcausarano** [comment]
Thank you for reporting this issue. I confirm I’m able to reproduce the issue locally. It has been added to our backlog and will be prioritized along with other issues. We'll update this issue once we have some updates about it.
